name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: Install Ruby and gems
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    # - name: Install postgresql tools
    #   run: |
    #     sudo apt update
    #     sudo apt install -y postgresql postgresql-contrib
    - run: |
        cp config/database.sample.yml config/database.yml
    - run: npm install
    - run: bundle exec rake test
    - run: npm test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      # Add or replace any other lints here
      - name: Security audit dependencies
        continue-on-error: true
        run: bin/bundler-audit --update
      - name: Security audit application code
        continue-on-error: true
        run: bin/brakeman -q -w2
      - name: Lint Ruby files
        continue-on-error: true
        run: bin/rubocop --parallel
